//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcIntro.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentID { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime CommentDateTime { get; set; }
        public int fk_UserID { get; set; }
        public long fk_BlogID { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
    }
}
