//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcIntro.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcIntro.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET — це безкоштовна веб-фреймворк для створення чудових веб-сайтів і веб-додатків за допомогою HTML, CSS і JavaScript..
        /// </summary>
        public static string AspNetFramework {
            get {
                return ResourceManager.GetString("AspNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC дає вам потужний, заснований на шаблонах спосіб створювати динамічні веб-сайти, які
        ///            дозволяє чітко розділяти проблеми та дає вам повний контроль над розміткою
        ///            для приємного, спритного розвитку..
        /// </summary>
        public static string descriptionASP {
            get {
                return ResourceManager.GetString("descriptionASP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet — це безкоштовне розширення Visual Studio, яке дозволяє легко додавати, видаляти та оновлювати бібліотеки та інструменти в проектах Visual Studio..
        /// </summary>
        public static string descriptionlib {
            get {
                return ResourceManager.GetString("descriptionlib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви можете легко знайти компанію з веб-хостингу, яка пропонує правильне поєднання функцій і ціни для ваших програм..
        /// </summary>
        public static string descriptionwebhosting {
            get {
                return ResourceManager.GetString("descriptionwebhosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отримайте більше бібліотек.
        /// </summary>
        public static string Getmorelib {
            get {
                return ResourceManager.GetString("Getmorelib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почати.
        /// </summary>
        public static string GetStart {
            get {
                return ResourceManager.GetString("GetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дiзнатися бiльше.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашня сторiнка.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веб-хостiнг.
        /// </summary>
        public static string webhosting {
            get {
                return ResourceManager.GetString("webhosting", resourceCulture);
            }
        }
    }
}
